#!/bin/bash

# CSS Compile
sass --load-path css/* > build/spry.css
sass --load-path css/* --style compressed > build/spry.min.css

# JavaScript Compile
# javaScript Minify Handled by Guard Plugins
cat js/* > build/spry.js

# Fonts Compile
#rm -rf build/font
#cp -r font build/font