#!/bin/bash

if [[ $1 == "website" ]]; then
	
	# build website
	cd web
	nanoc
	cd ..

elif [[ $1 == "css" ]]; then
		
	# compile css
	sass --load-path css/* > build/spry.css
	sass --load-path css/* --style compressed > build/spry.min.css

	# copy fonts 
	#rm -rf build/font
	#cp -r font build/font

elif [[ $1 == "javascript" ]]; then

	# compile javascript
	cat javascript/* > build/spry.js
fi